### PR TITLE
fix(ringmap): intercylinder colormap range

### LINKED ISSUE #103: sensitivity: use different colormap range when "divide by estimate" checked
If the divide by estimate block is checked on the sensitivity plot, then the default color range should change from (0.01, 0.1) to roughly (0.88, 0.90).

### LINKED ISSUE #105: Enabling intercylinder ringmap triggers infinite recursion
`Ringmap.view()` deactivates `template_subtraction` when `intercylinder_only` is activated. The change of `template_subtraction` triggers `view()` again.

### PR DESCRIPTION
**Pull request by nritsche**
- move intercyl_only changes to it's own callback (closes #105)
- set seperate colormap range for intercyl ringmap
- keep track of both colormap ranges (closes #103)

### CODE REVIEW

**Comment by ssiegelx** [comment]
In issue #103 I was referring to the sensitivity plot and having a separate colormap range for when the "divide by estimate" box is checked/unchecked.

It might also make sense to have a different range for the inter cylinder baseline ringmap, but the default range should not be (0.88, 0.9).  You could maybe use (-2, 2).

**Comment by nritsche** [comment]
> In issue #103 I was referring to the sensitivity plot and having a separate colormap range for when the "divide by estimate" box is checked/unchecked.
> 
> It might also make sense to have a different range for the inter cylinder baseline ringmap, but the default range should not be (0.88, 0.9). You could maybe use (-2, 2).

You're right, I mixed up the two issues. Thanks for the extra parameter. I applied the same schema to the sensitivity, so now both #103 and #105 are covered.

**Comment by nritsche** [comment]
Retry DeepCode

**Review by ssiegelx — APPROVED** [review]
Thanks @nritsche!

**Pull request merged**
